import React from "react";
import { ShieldAlert, AlertTriangle, Scale, Brain, Flame, FileX, Zap, CheckCircle2, XCircle, Building2, Lock, UserX } from "lucide-react";

export default function InstitutionalEvasionEssay() {
  return (
    <article className="prose max-w-none text-gray-800 leading-relaxed font-serif text-sm md:text-base space-y-6 animate-fade-in" id="institutionalevasion-article-text">
      
      {/* Header Banner */}
      <div className="text-center space-y-3 pb-6 border-b border-gray-100 max-w-3xl mx-auto">
        <span className="text-xs uppercase font-mono font-bold tracking-widest text-rose-650 bg-rose-50 px-2.5 py-1 rounded">
          Essay CX • Institutional Pathology & Critique of Procedural Whitewashing
        </span>
        <h1 className="text-2xl md:text-3xl font-extrabold text-slate-950 font-sans tracking-tight leading-tight">
          When Institutions Privatize Failure and Immunize Process: <br />
          <span className="text-xl md:text-2xl font-medium text-rose-800 block mt-2">
            The Epistemological Blindness of AI Consensus, Procedural Absolutism, and the Asymmetry of Individual Burden
          </span>
        </h1>
        <p className="text-sm text-gray-400 font-mono">
          By Dr. Yue Liu, Dr. Ying Liu, & Prof. Michael G. B. Drew • Epistemological Treatise • July 2026
        </p>
        <div className="text-xs text-rose-900 bg-rose-50 px-3 py-1 rounded border border-rose-100 inline-block font-sans font-semibold">
          第三十九讲：体制责任的制度性甩锅与形式程序的自我洗白——兼论AI共识如何将系统溃败全部转嫁于普通个体
        </div>
      </div>

      {/* Quote Block / Epigraph */}
      <div className="max-w-2xl mx-auto my-6 bg-slate-900 text-slate-100 p-5 rounded-xl space-y-4 shadow-inner border border-slate-800 font-mono text-xs md:text-sm">
        <div className="flex items-center gap-2 text-rose-400 border-b border-slate-800 pb-2">
          <Building2 className="w-4 h-4 text-rose-400" />
          <span className="font-bold uppercase tracking-wider">The Systemic Asymmetry</span>
        </div>
        <p className="italic text-slate-200 leading-relaxed">
          "When 95% of SCI papers are Cargo Cult garbage, the institution absolves itself of all institutional liability. When a student's thesis is flawed or a researcher challenges a disproven theory, the system places 100% of the financial, professional, and moral burden onto the vulnerable individual. Mainstream AI models like ChatGPT turn a blind eye to mountains of evidence simply because official authorities refuse to issue self-incriminating confessions. This is not scientific rigor; it is procedural tyranny."
        </p>
        <p className="text-[10px] text-slate-400 text-right mt-1 font-sans">
          — Dr. Yue Liu, *Critique of Institutional Evasion and Procedural Whitewashing*, July 2026
        </p>
      </div>

      {/* Section 1: The Unspoken Reality of Systemic Liability Evasion */}
      <div className="space-y-4 pt-4 text-left">
        <h3 className="text-xl font-bold text-gray-955 font-sans tracking-tight flex items-center gap-2 text-rose-955 border-b border-gray-100 pb-1.5">
          <span className="text-rose-600 font-mono">I.</span> What AI Consensus Cannot Admit: Institutional Immunization & Individual Burden
          <span className="text-xs font-sans text-gray-400 font-normal ml-auto">避而不谈的真相：体制的自我免疫与风险的绝对转嫁</span>
        </h3>
        <p>
          In the sanitized narratives generated by AI models like ChatGPT, academic systems are depicted as self-correcting mechanisms governed by impartial peer review. Yet this sanitized picture conceals a glaring structural injustice:
        </p>
        <p>
          If 95% of SCI publications are Cargo Cult garbage, and if academic institutions routinely fail in their fundamental duty to uphold mathematical and physical truth, <strong>the institution bears zero institutional, financial, or legal responsibility.</strong>
        </p>
        <p>
          Instead, all risks, lost years, tuition expenses, and career casualties are privatized onto ordinary individuals—students, early-career researchers, and whistleblowers—while university administrators, editorial boards, and review committees enjoy complete immunity.
        </p>
      </div>

      {/* Section 2: The Parallel: University Accountability and the Thesis Trap */}
      <div className="space-y-4 text-left">
        <h3 className="text-xl font-bold text-gray-955 font-sans tracking-tight flex items-center gap-2 text-rose-955 border-b border-gray-100 pb-1.5">
          <span className="text-rose-600 font-mono">II.</span> The Structural Parallel: Who Pays for Institutional Negligence?
          <span className="text-xs font-sans text-gray-400 font-normal ml-auto">同构的病理：导师、评审与答辩委员会失职，凭什么由个体买单？</span>
        </h3>
        <p>
          Consider how academic institutions handle failed degrees or thesis controversies (such as high-profile graduate thesis cases discussed in public commentary).
        </p>

        <div className="grid md:grid-cols-2 gap-4 my-4 font-sans text-xs md:text-sm">
          <div className="p-4 bg-slate-50 border border-slate-200 rounded-xl space-y-2">
            <h5 className="font-bold text-slate-900 flex items-center gap-1.5 text-xs font-mono uppercase">
              <UserX className="w-4 h-4 text-slate-700 shrink-0" />
              1. Institutional Delegation vs. Zero Liability
            </h5>
            <p className="text-slate-800 leading-relaxed font-serif text-xs">
              Advisors, thesis reviewers, and defense committees are appointed by the university—not hired independently by the student. When a thesis is later deemed invalid or flawed, these institutional agents either approved it out of negligence, incompetence, or tacit complicity. Yet the institution rarely compensates the student for wasted tuition, lost years, or reputational damage.
            </p>
          </div>

          <div className="p-4 bg-rose-50/90 border border-rose-200 rounded-xl space-y-2">
            <h5 className="font-bold text-rose-950 flex items-center gap-1.5 text-xs font-mono uppercase">
              <ShieldAlert className="w-4 h-4 text-rose-600 shrink-0" />
              2. Consumer Protection & Academic Fraud
            </h5>
            <p className="text-rose-900 leading-relaxed font-serif text-xs">
              If an educational institution charges fees while providing incompetent guidance and rubber-stamping substandard work, it commits consumer fraud. True accountability demands that institutions bear direct financial compensation when their appointed committees fail in their duty.
            </p>
          </div>
        </div>
      </div>

      {/* Section 3: ChatGPT's Epistemological Blind Spot: "If Authority Is Silent, Evidence Does Not Exist" */}
      <div className="space-y-4 text-left">
        <h3 className="text-xl font-bold text-gray-955 font-sans tracking-tight flex items-center gap-2 text-rose-955 border-b border-gray-100 pb-1.5">
          <span className="text-rose-600 font-mono">III.</span> The AI Blind Spot: "If Authorities Don't Admit It, We Can't See It"
          <span className="text-xs font-sans text-gray-400 font-normal ml-auto">ChatGPT的认识论盲区：只要主流机构不承认，证据就“不存在”</span>
        </h3>
        <p>
          The fundamental flaw in ChatGPT's logic is its reliance on official recognition as a prerequisite for empirical reality.
        </p>
        <p>
          When critics present mountains of mathematical proofs showing that thin-film impedance matching violates wave superposition, ChatGPT responds: <em>"Without an official statement from an international scientific body or a top journal consensus, we cannot conclude that impedance matching is wrong or that 95% of SCI papers are garbage."</em>
        </p>

        <div className="bg-rose-50 border border-rose-200 rounded-xl p-4 font-sans text-xs md:text-sm space-y-2 my-3">
          <h5 className="font-bold text-rose-950 flex items-center gap-2 font-mono uppercase">
            <AlertTriangle className="w-4 h-4 text-rose-600" />
            The Absurdity of Demanding Official Confessions (等贼发自白书的荒诞):
          </h5>
          <p className="text-rose-900 leading-relaxed font-serif">
            This logic implies that evidence does not exist until the perpetrator of an error officially acknowledges it! Waiting for corrupt academic journals or grant committees to officially declare that their own published literature is Cargo Cult garbage is an exercise in futility. Scientific evidence exists independently of administrative rubber-stamps.
          </p>
        </div>
      </div>

      {/* Section 4: Procedural Absolutism: The Circular Wall of Peer Review */}
      <div className="space-y-4 text-left">
        <h3 className="text-xl font-bold text-gray-955 font-sans tracking-tight flex items-center gap-2 text-rose-955 border-b border-gray-100 pb-1.5">
          <span className="text-rose-600 font-mono">IV.</span> Procedural Absolutism: How Editors Dismiss Appeals with Seamless Formalities
          <span className="text-xs font-sans text-gray-400 font-normal ml-auto">形式程序的自我洗白：理直气壮的“合规”遮蔽了实性真理</span>
        </h3>
        <p>
          When an author submits a rigorous appeal proving that peer-review comments contained fatal mathematical errors or violated undergraduate wave mechanics, editorial offices across the globe respond with identical, cold uniformity:
        </p>
        <blockquote className="border-l-4 border-slate-900 pl-4 py-1.5 italic bg-slate-100 my-3 text-slate-800 text-xs md:text-sm font-mono">
          "Your appeal has been considered. However, our peer-review process was conducted strictly in accordance with journal guidelines and formal protocols. The decision stands."
        </blockquote>
        <p>
          Notice how the substance of the mathematical correction is completely ignored. The editorial apparatus substitutes <strong>procedural compliance</strong> for <strong>substantive truth</strong>.
        </p>

        <div className="bg-slate-900 text-slate-100 p-4.5 rounded-xl border border-slate-800 font-sans text-xs md:text-sm space-y-3 my-3 shadow-md">
          <h5 className="font-bold text-rose-400 flex items-center gap-2 font-mono text-xs uppercase tracking-wider">
            <Lock className="w-4 h-4 text-rose-400" />
            The Closed Loop of Procedural Tyranny (形式程序闭环的暴政):
          </h5>
          <ul className="list-disc pl-5 space-y-2 text-slate-200 font-serif leading-relaxed">
            <li>
              <strong>Step 1:</strong> The reviewer evaluates the paper using disproven impedance matching dogma.
            </li>
            <li>
              <strong>Step 2:</strong> The editor rejects the paper based on the reviewer's flawed report.
            </li>
            <li>
              <strong>Step 3:</strong> The author submits middle-school algebra proving the reviewer's error.
            </li>
            <li>
              <strong>Step 4:</strong> The editor dismisses the appeal by declaring: <em>"The review followed proper formal protocols."</em>
            </li>
          </ul>
          <p className="text-slate-300 font-mono text-xs pt-2 border-t border-slate-800">
            This circular logic immunizes the journal against correction, allowing Cargo Cult science to flourish behind the shield of "seamless procedures."
          </p>
        </div>
      </div>

      {/* Section 5: Conclusion */}
      <div className="space-y-4 text-left pt-4 border-t border-gray-200">
        <h3 className="text-xl font-bold text-gray-955 font-sans tracking-tight flex items-center gap-2 text-rose-955 border-b border-gray-100 pb-1.5">
          <span className="text-rose-600 font-mono">V.</span> Conclusion: Breaking the Shield of Procedural Evasion
          <span className="text-xs font-sans text-gray-400 font-normal ml-auto">结论：击碎程序逃避的护城河，挺立第一性原理的真理正义</span>
        </h3>
        <p>
          A scientific system that privatizes all failure onto vulnerable individuals while using "procedural compliance" to shield institutional negligence is morally and epistemologically bankrupt.
        </p>
        <p>
          Science does not belong to editorial committees that hide behind formal protocols, nor to AI models that equate official silence with lack of evidence. It belongs to independent thinkers who hold institutions accountable to pure logic, elementary algebra, and physical reality.
        </p>
        <p className="font-bold text-center text-slate-900 border-t border-gray-100 pt-4 font-sans text-sm md:text-base">
          "When formal procedures are used to whitewash substantive errors, procedural justice becomes procedural tyranny. True science demands that institutions bear responsibility for their failures and yield to the absolute authority of wave mechanics."
        </p>
      </div>

    </article>
  );
}
